[package]
name = "port-exporter"
version = "0.1.0"
authors = ["Karol Kozakowski <cosaquee@gmail.com>"]

[dependencies]
prometheus = "0.3"
futures = "0.1.14"
hyper = "0.11.2"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
clap = "2.31.2"
slog = "2.2.1"
slog-term = "2.3.0"